val list1= List(1,2,3,4,5,7,8,9,10,20)
val rdd=sc.parallelize(list1)
val out=rdd.collect()
print(out)
rdd.partitions.size 
rdd.map(y=>y*y).collect()
rdd.flatMap(x=>x+"!").collect()
rdd.filter(x=>x%2==0).collect()
rdd.top(5)
rdd.count()
val rdd2=sc.parallelize(List("hello how are you"))
val out1=rdd2.collect()
rdd2.flatMap(x=>x+",").collect()
rdd2.map(x=>x+",").collect()
